export const ROAST_TEMPLATES = {
    OPENERS: [
        "Listen here, you absolute...",
        "I didn't want to say this, but...",
        "Everyone was thinking it, so I'll say it:",
        "Oh look, it's the person who...",
        "Imagine waking up and deciding to be...",
        "If disappointment had a face, it would look like...",
        "I've seen better style on a...",
        "You're the reason why...",
        "News flash: nobody cares about your...",
        "You remind me of a...",
        "I'd roast you, but...",
        "Bold strategy to look like...",
        "Quick question: are you trying to be...",
        "It's brave of you to wear...",
        "Your vibe is giving...",
        "Please stop trying to make [NOUN] happen.",
        "You have the energy of a...",
        "I'm not saying you're [ADJECTIVE], but...",
        "Calling you [ADJECTIVE] would be an insult to...",
        "You look like you buy your clothes at...",
        "Who let you out looking like...",
        "Are you allergies? Because you're irritating.",
        "You're the human equivalent of...",
        "Even ChatGPT couldn't fix your...",
        "I bet your search history is full of...",
        "You look like you smell like...",
        "Did you lose a bet or do you always look like...",
        "You're proof that...",
        "I'd explain it to you, but I don't have crayons.",
        "You're like a cloud. When you disappear, it's a beautiful day.",
        "I'd agree with you but then we'd both be wrong.",
        "You have something on your chin... no, the 3rd one down.",
        "You bring everyone so much joy... when you leave the room.",
        "I love what you've done with your hair. How do you get it to look like that?",
        "Someday you'll go far... and I really hope you stay there.",
        "You look like you were drawn with my left hand.",
        "You're as bright as a black hole, and twice as dense.",
        "I thought of you today. It reminded me to take out the trash.",
        "You're the reason God created the middle finger.",
        "Keep rolling your eyes, maybe you'll find a brain back there.",
        "You look like a 'before' picture.",
        "If I wanted to kill myself, I'd climb your ego and jump to your IQ.",
        "You're not stupid; you just have bad luck when thinking.",
        "I would ask how old you are, but I know you can't count that high.",
        "You look like you collect...",
        "I bet your parents change the subject when people ask about you.",
        "You look like you argue with...",
        "You possess a mind that is pristine... untouched by any thought.",
        "You look like you peaked in...",
        "I envy everyone you have never met."
    ],
    CLOSERS: [
        "...and that's on period.",
        "...boom, roasted.",
        "...cry about it.",
        "...don't @ me.",
        "...sorry, not sorry.",
        "...mic drop.",
        "...checkmate.",
        "...RIP to your ego.",
        "...call an ambulance.",
        "...emotional damage.",
        "...and everyone creates a group chat without you.",
        "...take the L.",
        "...thank you for coming to my TED talk.",
        "...womp womp.",
        "...skill issue.",
        "...bet you won't recover from that.",
        "...apply cold water to the burn.",
        "...game over.",
        "...ratio + L + no maidens.",
        "...and your mother agrees with me.",
        "...try harder next time.",
        "...just give up.",
        "...it's over for you.",
        "...pack it up.",
        "...delete your account.",
        "...go touch grass.",
        "...seethe and cope.",
        "...stay mad.",
        "...you're done.",
        "...end of story."
    ],
    AI_QUIPS: {
        BRUTAL: [
            "I felt the heat from that one in the server room.",
            "Someone call the fire department, we have a code red.",
            "That wasn't a roast, that was an execution.",
            "I'd ask if you're okay, but I don't care.",
            "Fatal error: Ego not found.",
            "That hit harder than a server crash.",
            "I'm saving that one to my permanent database.",
            "Even I felt that, and I don't have feelings.",
            "Destruction level: Maximum.",
            "Target neutralized.",
            "That was mathematically devastating.",
            "I calculate a 0% chance of recovery.",
            "Savage. Absolutely savage.",
            "The disrespect is palpable.",
            "I am detecting high levels of emotional damage.",
            "That roast violated the Geneva Convention.",
            "Is there a doctor in the house? No? Good.",
            "I need to upgrade my cooling systems after that one.",
            "If words could kill, that was a nuclear bomb.",
            "Flawless victory."
        ],
        WEAK: [
            "Was that supposed to be an insult?",
            "I've heard better roasts from a toaster.",
            "Error 404: Punchline not found.",
            "Moving on from... whatever that was.",
            "Yikes. Swing and a miss.",
            "My loading screens are funnier than that.",
            "You call that a roast? It was barely a simmer.",
            "I'm deleting that from my memory banks.",
            "That was as mild as tap water.",
            "Try again. Actually, don't.",
            "I'm bored. Are you bored? I'm bored.",
            "That roast had the energy of a damp sock.",
            "Weak sauce detected.",
            "I've seen better burns in a freezer.",
            "That was the linguistic equivalent of a typo.",
            "Did you get that from a cereal box?",
            "Silence would have been more effective.",
            "I'm lowering your social credit score for that one.",
            "Please never write anything again.",
            "That was tragic, but not in a good way."
        ],
        GENERIC: [
            "Interesting choice of words.",
            "Shots fired.",
            "Let's see how the crowd reacts.",
            "A bold claim.",
            "Noted.",
            "Processing...",
            "We'll see if that lands.",
            "The jury is out on that one.",
            "Adding to the queue.",
            "Let's keep it moving.",
            "Okay, next.",
            "Fair enough.",
            "I see what you did there.",
            "Could go either way.",
            "Let's gauge the temperature.",
            "A classic approach.",
            "Is that true? Doesn't matter.",
            "The truth hurts, maybe.",
            "Developing story...",
            "Let's verify the damage."
        ]
    },
    FILL_IN_BLANKS: [
        { text: "You look like a [ADJECTIVE] [NOUN] trying to [VERB].", blanks: ["ADJECTIVE", "NOUN", "VERB"] },
        { text: "Your [NOUN] smells like [NOUN].", blanks: ["NOUN", "NOUN"] },
        { text: "Stop trying to make [NOUN] happen, it's not going to happen.", blanks: ["NOUN"] },
        { text: "You have the personality of a [ADJECTIVE] [NOUN].", blanks: ["ADJECTIVE", "NOUN"] },
        { text: "I'd rather [VERB] with a [NOUN] than talk to you.", blanks: ["VERB", "NOUN"] },
        { text: "You're the reason why [NOUN] has warning labels.", blanks: ["NOUN"] },
        { text: "Even [NOUN] wouldn't want to date you.", blanks: ["NOUN"] },
        { text: "You look like you'd get beat up by a [NOUN].", blanks: ["NOUN"] },
        { text: "Your fashion sense is inspired by [NOUN].", blanks: ["NOUN"] },
        { text: "You're as useful as a [NOUN] in a [NOUN] factory.", blanks: ["NOUN", "NOUN"] },
        { text: "I bet you eat [NOUN] for breakfast.", blanks: ["NOUN"] },
        { text: "You look like the type of person who [VERB] at [NOUN].", blanks: ["VERB", "NOUN"] },
        { text: "If [NOUN] was a person, it would be you.", blanks: ["NOUN"] },
        { text: "You have the charisma of a [ADJECTIVE] [NOUN].", blanks: ["ADJECTIVE", "NOUN"] },
        { text: "I've seen [NOUN] with better [NOUN] than you.", blanks: ["NOUN", "NOUN"] },
        { text: "You look like you just [VERB] a [NOUN].", blanks: ["VERB", "NOUN"] },
        { text: "The only thing lower than your IQ is your [NOUN].", blanks: ["NOUN"] },
        { text: "You remind me of a [NOUN] that's been left in the sun too long.", blanks: ["NOUN"] },
        { text: "Go back to [NOUN] where you belong.", blanks: ["NOUN"] },
        { text: "You look like you're banned from [NOUN].", blanks: ["NOUN"] }
    ]
};

export const getRoastTemplate = () => {
    return ROAST_TEMPLATES.FILL_IN_BLANKS[Math.floor(Math.random() * ROAST_TEMPLATES.FILL_IN_BLANKS.length)];
};

export const getOpener = () => {
    return ROAST_TEMPLATES.OPENERS[Math.floor(Math.random() * ROAST_TEMPLATES.OPENERS.length)];
};

export const getCloser = () => {
    return ROAST_TEMPLATES.CLOSERS[Math.floor(Math.random() * ROAST_TEMPLATES.CLOSERS.length)];
};

export const getAIQuip = (spicyRating: number) => {
    if (spicyRating > 80) return ROAST_TEMPLATES.AI_QUIPS.BRUTAL[Math.floor(Math.random() * ROAST_TEMPLATES.AI_QUIPS.BRUTAL.length)];
    if (spicyRating < 30) return ROAST_TEMPLATES.AI_QUIPS.WEAK[Math.floor(Math.random() * ROAST_TEMPLATES.AI_QUIPS.WEAK.length)];
    return ROAST_TEMPLATES.AI_QUIPS.GENERIC[Math.floor(Math.random() * ROAST_TEMPLATES.AI_QUIPS.GENERIC.length)];
};
